apiVersion: v1
kind: Service
metadata:
  name: leaderboard-metrics
  namespace: leaderboard
  labels:
    app: leaderboard
spec:
  selector:
    app: leaderboard
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: leaderboard-monitor
  namespace: leaderboard
  labels:
    app: leaderboard
spec:
  selector:
    matchLabels:
      app: leaderboard
  endpoints:
  - port: metrics
    path: /metrics
    interval: 5s
