global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'exchange-service'
    static_configs:
      - targets: ['exchange-service:9090']
    metrics_path: /metrics
    scrape_interval: 5s
